name: Python CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11.4
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.4'
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Run code formatting checks with black
      run: |
        black --check black --line-length 79 src/ tests/
    - name: Run tests
      run: |
        pytest

